#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo -e "\n\033[0;33mHusky pre-commit hook\033[0m" "HUSKY_GIT_PARAMS" $HUSKY_GIT_PARAMS $0 $1 $2 $3 $4 $5 $m

yarn run build-all || exit 1
git add . # add any new files that were built

bash ./_bin/commit-all-submodules.sh . "auto commit-all-submodules projects pre-commit monorepo"